source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'builder'
gem 'html-proofer'
gem 'kramdown'
gem 'kramdown-parser-gfm'
# gem 'middleman'
# gem 'middleman-dato', '~> 0.10.0'
gem 'middleman-dotenv'
gem 'middleman-inline_svg'
gem 'middleman-livereload'
gem 'middleman-minify-html'
# gem 'middleman-paginate'
gem 'nokogiri'
gem 'rake'
